[package]
authors = ['Interlay']
description = 'Treasury module'
edition = '2018'
name = 'treasury'
version = '2.0.0-rc.4'

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'safe-mix/std',
	'sp-core/std',
	'sp-io/std',
	'sp-runtime/std',
	'sp-std/std',
    'system/std',
	'pallet-balances/std',
#	'x-core/std',
]

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.0'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-rc.4'
tag = 'v2.0.0-rc4'

[dependencies.safe-mix]
default-features = false
version = '1.0.0'

[dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-rc.4'
tag = 'v2.0.0-rc4'

[dependencies.sp-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-rc.4'
tag = 'v2.0.0-rc4'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-rc.4'
tag = 'v2.0.0-rc4'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-rc.4'
tag = 'v2.0.0-rc4'

[dependencies.sp-arithmetic]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-rc.4'
tag = 'v2.0.0-rc4'

[dependencies.system]
default-features = false
package = 'frame-system'
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-rc.4'
tag = 'v2.0.0-rc4'

[dependencies.pallet-balances]
default-features = false
package = 'pallet-balances'
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-rc.4'
tag = 'v2.0.0-rc4'

[dependencies.iroha_client_no_std]
default-features = false
path = "../../../../../iroha/iroha_client_no_std"

#[dependencies.x-core]
#default-features = false
#path = '../core'

[dev-dependencies]
mocktopus = "0.7.0"

